//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPCommissionsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commission
    {
        public Commission()
        {
            this.CommissionRules = new HashSet<CommissionRule>();
        }
    
        public int Id { get; set; }
        public string Value { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int PlanId { get; set; }
        public int CommissionTypeId { get; set; }
    
        public virtual CommissionPayType CommissionPayType { get; set; }
        public virtual Deaeler Deaeler { get; set; }
        public virtual Plan Plan { get; set; }
        public virtual CommissionType CommissionType { get; set; }
        public virtual ICollection<CommissionRule> CommissionRules { get; set; }
    }
}
