//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPCommissionsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommissionPayType
    {
        public CommissionPayType()
        {
            this.Commissions = new HashSet<Commission>();
        }
    
        public int Id { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Commission> Commissions { get; set; }
    }
}
