//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPCommissionsModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Deaeler> Deaelers1 { get; set; }
        public virtual DbSet<Operator> Operators { get; set; }
        public virtual DbSet<Commission> Commissions { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<CommissionType> CommissionTypes { get; set; }
        public virtual DbSet<CommissionPayType> CommissionPayTypes { get; set; }
        public virtual DbSet<CommissionRule> CommissionRules { get; set; }
    }
}
